
FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y \
    gcc \
    g++ \
    libffi-dev \
    libssl-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN echo $PATH

RUN pip install ansible ansible-runner


WORKDIR /app


COPY . /app/